/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Parse Document Endpoint */
        post: operations["parse_document_endpoint_api_v1_documents_parse_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analyses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Analysis */
        post: operations["create_analysis_api_v1_analyses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalysisResult */
        AnalysisResult: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Job Title */
            job_title: string | null;
            /** Company Name */
            company_name: string | null;
            /** Overall Score */
            overall_score: number;
            /** Category Scores */
            category_scores: components["schemas"]["CategoryScore"][];
            /** Matches */
            matches: components["schemas"]["RequirementMatch"][];
            /**
             * Output Language
             * @enum {string}
             */
            output_language: "tr" | "en";
            /**
             * Matcher
             * @enum {string}
             */
            matcher: "llm" | "keyword";
        };
        /** Body_create_analysis_api_v1_analyses_post */
        Body_create_analysis_api_v1_analyses_post: {
            /** Job Text */
            job_text: string;
            /**
             * Output Language
             * @enum {string}
             */
            output_language: "tr" | "en";
            /** Cv Text */
            cv_text?: string | null;
            /** Cv File */
            cv_file?: string | null;
        };
        /** Body_parse_document_endpoint_api_v1_documents_parse_post */
        Body_parse_document_endpoint_api_v1_documents_parse_post: {
            /** File */
            file: string;
        };
        /** CategoryScore */
        CategoryScore: {
            category: components["schemas"]["RequirementCategory"];
            /** Score */
            score: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Importance
         * @enum {string}
         */
        Importance: "must_have" | "nice_to_have";
        /**
         * MatchStatus
         * @enum {string}
         */
        MatchStatus: "met" | "partial" | "missing";
        /** ParsedDocument */
        ParsedDocument: {
            /** Text */
            text: string;
            /**
             * Source
             * @enum {string}
             */
            source: "pdf" | "docx" | "text";
            /** Char Count */
            char_count: number;
            /** Page Count */
            page_count?: number | null;
        };
        /**
         * RequirementCategory
         * @enum {string}
         */
        RequirementCategory: "technical_skill" | "tool" | "experience" | "education" | "language" | "soft_skill";
        /** RequirementMatch */
        RequirementMatch: {
            /** Requirement Text */
            requirement_text: string;
            category: components["schemas"]["RequirementCategory"];
            importance: components["schemas"]["Importance"];
            status: components["schemas"]["MatchStatus"];
            /** Evidence */
            evidence: string | null;
            /** Explanation */
            explanation: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    parse_document_endpoint_api_v1_documents_parse_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_parse_document_endpoint_api_v1_documents_parse_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParsedDocument"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_analysis_api_v1_analyses_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_analysis_api_v1_analyses_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
